// packages/solid-elements/src/components/account-menu.ts
// AUTHORED-BY Claude Opus 4.8 (Fable unavailable) — re-review/upgrade candidate
//
// <jeswr-account-menu> — the top-right account control: avatar + display name,
// opening a dropdown with the WebID and a Sign out action.
//
// DECOUPLED BY DESIGN (ports app-shell's React AccountMenu): everything is a
// prop/attribute — `webid`, `name`, `avatar-url` — and a `<slot>` lets the host
// inject extra menu items above Sign out. The avatar shows the image, or the
// `initials(name)` fallback. Emits a `sign-out` CustomEvent on the sign-out
// action; the host wires its own session teardown to that.

import { css, html, LitElement, nothing } from "lit";
import { tokenStyles } from "../theme-tokens.js";

/** Initials from a display name, for the avatar fallback. Exported for tests. */
export function initials(name: string): string {
  const parts = name.trim().split(/\s+/).filter(Boolean);
  if (parts.length === 0) return "?";
  if (parts.length === 1) return parts[0].slice(0, 2).toUpperCase();
  return (parts[0][0] + parts[parts.length - 1][0]).toUpperCase();
}

export class JeswrAccountMenu extends LitElement {
  static properties = {
    webId: { type: String, attribute: "webid" },
    name: { type: String },
    avatarUrl: { type: String, attribute: "avatar-url" },
    _open: { state: true },
  };

  /** The authenticated user's WebID (shown under the name; the canonical id). */
  declare webId: string | null;
  /** Human display name (foaf:name). Falls back to the WebID, then "Account". */
  declare name: string | null;
  /** Avatar image URL (foaf:img / vcard:hasPhoto). Falls back to initials. */
  declare avatarUrl: string | null;
  private declare _open: boolean;

  private readonly onDocPointer = (e: Event): void => {
    // Close when a click/tap lands outside this element.
    if (!e.composedPath().includes(this)) this._open = false;
  };

  static styles = [
    tokenStyles,
    css`
      :host {
        display: inline-block;
        position: relative;
      }
      .trigger {
        display: inline-flex;
        align-items: center;
        gap: 0.5rem;
        height: auto;
        padding: 0.375rem 0.5rem;
        border: 1px solid transparent;
        border-radius: var(--jeswr-radius);
        background: transparent;
        color: inherit;
        font: inherit;
        cursor: pointer;
      }
      .trigger:hover {
        background: var(--jeswr-accent);
        color: var(--jeswr-accent-fg);
      }
      .trigger:focus-visible {
        outline: 2px solid var(--jeswr-ring);
        outline-offset: 2px;
      }
      .avatar {
        display: inline-flex;
        align-items: center;
        justify-content: center;
        width: 1.75rem;
        height: 1.75rem;
        border-radius: 9999px;
        background: var(--jeswr-accent);
        color: var(--jeswr-accent-fg);
        font-size: 0.75rem;
        font-weight: 600;
        overflow: hidden;
        flex: none;
      }
      .avatar img {
        width: 100%;
        height: 100%;
        object-fit: cover;
      }
      .trigger-name {
        max-width: 8rem;
        overflow: hidden;
        text-overflow: ellipsis;
        white-space: nowrap;
        font-size: 0.875rem;
        font-weight: 500;
      }
      .menu {
        position: absolute;
        right: 0;
        top: calc(100% + 0.25rem);
        min-width: 16rem;
        max-width: 20rem;
        padding: 0.375rem;
        border: 1px solid var(--jeswr-border);
        border-radius: var(--jeswr-radius);
        background: var(--jeswr-popover);
        color: var(--jeswr-popover-fg);
        box-shadow: 0 4px 16px rgb(0 0 0 / 12%);
        z-index: 50;
      }
      .identity {
        display: flex;
        flex-direction: column;
        gap: 0.125rem;
        padding: 0.375rem 0.5rem;
      }
      .identity-name {
        font-weight: 500;
        overflow: hidden;
        text-overflow: ellipsis;
        white-space: nowrap;
      }
      .identity-webid {
        font-size: 0.75rem;
        color: var(--jeswr-muted-fg);
        overflow: hidden;
        text-overflow: ellipsis;
        white-space: nowrap;
      }
      .sep {
        height: 1px;
        margin: 0.375rem 0;
        background: var(--jeswr-border);
        border: 0;
      }
      .item {
        display: flex;
        width: 100%;
        align-items: center;
        gap: 0.5rem;
        padding: 0.5rem;
        border: 0;
        border-radius: calc(var(--jeswr-radius) - 0.25rem);
        background: transparent;
        color: inherit;
        font: inherit;
        text-align: left;
        cursor: pointer;
      }
      .item:hover {
        background: var(--jeswr-accent);
        color: var(--jeswr-accent-fg);
      }
      .item:focus-visible {
        outline: 2px solid var(--jeswr-ring);
        outline-offset: -2px;
      }
      .icon {
        width: 1rem;
        height: 1rem;
        flex: none;
      }
    `,
  ];

  constructor() {
    super();
    this.webId = null;
    this.name = null;
    this.avatarUrl = null;
    this._open = false;
  }

  override disconnectedCallback(): void {
    super.disconnectedCallback();
    document.removeEventListener("pointerdown", this.onDocPointer, true);
  }

  private toggle = (): void => {
    this._open = !this._open;
    if (this._open) {
      document.addEventListener("pointerdown", this.onDocPointer, true);
    } else {
      document.removeEventListener("pointerdown", this.onDocPointer, true);
    }
  };

  private signOut = (): void => {
    this._open = false;
    document.removeEventListener("pointerdown", this.onDocPointer, true);
    this.dispatchEvent(new CustomEvent("sign-out", { bubbles: true, composed: true }));
  };

  private onKeyDown = (e: KeyboardEvent): void => {
    if (e.key === "Escape" && this._open) {
      this._open = false;
      document.removeEventListener("pointerdown", this.onDocPointer, true);
    }
  };

  override render() {
    const displayName = this.name || this.webId || "Account";
    const hasIdentity = Boolean(this.name || this.webId);
    return html`
      <button
        part="trigger"
        class="trigger"
        type="button"
        aria-haspopup="menu"
        aria-expanded=${this._open ? "true" : "false"}
        aria-label="Account menu"
        @click=${this.toggle}
        @keydown=${this.onKeyDown}
      >
        <span part="avatar" class="avatar" aria-hidden="true">
          ${
            this.avatarUrl
              ? html`<img src=${this.avatarUrl} alt="" />`
              : hasIdentity
                ? initials(displayName)
                : "?"
          }
        </span>
        <span part="trigger-name" class="trigger-name">${this.name || "Signed in"}</span>
      </button>
      ${
        this._open
          ? html`
              <div part="menu" class="menu" role="menu" @keydown=${this.onKeyDown}>
                <div part="identity" class="identity">
                  <span class="identity-name">${displayName}</span>
                  ${
                    this.webId
                      ? html`<span part="webid" class="identity-webid">${this.webId}</span>`
                      : nothing
                  }
                </div>
                <hr class="sep" />
                <slot></slot>
                <button part="sign-out" class="item" type="button" role="menuitem" @click=${this.signOut}>
                  <svg class="icon" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true">
                    <path d="M9 21H5a2 2 0 0 1-2-2V5a2 2 0 0 1 2-2h4M16 17l5-5-5-5M21 12H9" />
                  </svg>
                  Sign out
                </button>
              </div>
            `
          : nothing
      }
    `;
  }
}

if (typeof customElements !== "undefined" && !customElements.get("jeswr-account-menu")) {
  customElements.define("jeswr-account-menu", JeswrAccountMenu);
}

declare global {
  interface HTMLElementTagNameMap {
    "jeswr-account-menu": JeswrAccountMenu;
  }
}

// packages/app-shell/src/components/account-menu.tsx
// AUTHORED-BY Claude Opus 4.8 (Fable unavailable) — re-review/upgrade candidate
//
// AccountMenu — the top-right account control: avatar + display name, opening a
// dropdown with the WebID, optional Profile / Settings entries, and Sign out.
//
// DECOUPLED BY DESIGN: unlike PM's version (which read `useSession()` and called
// `toast`), this takes everything as PROPS — `webId`, `displayName`, `avatarUrl`,
// and the `onSignOut` / `onProfile` / `onSettings` callbacks — so it has no
// app-specific coupling and works in any app (Vite or Next). The host wires its
// own session + navigation + toast in the callbacks. Profile/Settings entries
// render ONLY when their callback (or href) is supplied.

import { LogOut, Settings, UserRound } from "lucide-react";
import type * as React from "react";
import {
  Avatar,
  AvatarFallback,
  AvatarImage,
  Button,
  DropdownMenu,
  DropdownMenuContent,
  DropdownMenuItem,
  DropdownMenuLabel,
  DropdownMenuSeparator,
  DropdownMenuTrigger,
} from "./primitives.js";

/** Initials from a display name, for the avatar fallback. Exported for tests. */
export function initials(name: string): string {
  const parts = name.trim().split(/\s+/).filter(Boolean);
  if (parts.length === 0) return "?";
  if (parts.length === 1) return parts[0].slice(0, 2).toUpperCase();
  return (parts[0][0] + parts[parts.length - 1][0]).toUpperCase();
}

export interface AccountMenuProps {
  /** The authenticated user's WebID (shown under the name; the canonical id). */
  webId?: string | null;
  /** Human display name (foaf:name). Falls back to the WebID, then "Account". */
  displayName?: string | null;
  /** Avatar image URL (foaf:img / vcard:hasPhoto). Falls back to initials. */
  avatarUrl?: string | null;
  /** Sign-out callback (required — the menu always offers Sign out). */
  onSignOut: () => void;
  /** Optional: open the profile. Renders a "Profile" item when provided. */
  onProfile?: () => void;
  /** Optional: open settings. Renders a "Settings" item when provided. */
  onSettings?: () => void;
  /** Optional extra menu items rendered above Sign out (e.g. app-specific links). */
  children?: React.ReactNode;
}

/** Header account control: avatar + name, with WebID, optional nav, and sign-out. */
export function AccountMenu({
  webId,
  displayName,
  avatarUrl,
  onSignOut,
  onProfile,
  onSettings,
  children,
}: AccountMenuProps) {
  const name = displayName || webId || "Account";
  const hasIdentity = Boolean(displayName || webId);

  return (
    <DropdownMenu>
      <DropdownMenuTrigger asChild>
        <Button variant="ghost" className="h-auto gap-2 px-2 py-1.5" aria-label="Account menu">
          <Avatar className="size-7">
            {avatarUrl ? <AvatarImage src={avatarUrl} alt="" /> : null}
            <AvatarFallback>
              {hasIdentity ? initials(name) : <UserRound className="size-4" aria-hidden="true" />}
            </AvatarFallback>
          </Avatar>
          <span className="hidden max-w-32 truncate text-sm font-medium sm:inline">
            {displayName || "Signed in"}
          </span>
        </Button>
      </DropdownMenuTrigger>
      <DropdownMenuContent align="end" className="w-64">
        <DropdownMenuLabel className="flex flex-col gap-0.5">
          <span className="truncate font-medium">{name}</span>
          {webId ? (
            <span className="truncate text-xs font-normal text-muted-foreground">{webId}</span>
          ) : null}
        </DropdownMenuLabel>
        <DropdownMenuSeparator />
        {onProfile ? (
          <DropdownMenuItem onClick={onProfile}>
            <UserRound className="size-4" aria-hidden="true" />
            Profile
          </DropdownMenuItem>
        ) : null}
        {onSettings ? (
          <DropdownMenuItem onClick={onSettings}>
            <Settings className="size-4" aria-hidden="true" />
            Settings
          </DropdownMenuItem>
        ) : null}
        {children}
        {onProfile || onSettings || children ? <DropdownMenuSeparator /> : null}
        <DropdownMenuItem onClick={onSignOut}>
          <LogOut className="size-4" aria-hidden="true" />
          Sign out
        </DropdownMenuItem>
      </DropdownMenuContent>
    </DropdownMenu>
  );
}
